export const currency = [
  {
    flag: 'fi fi-us',
    code: 'USD',
    desc: 'US Dollar',
    symbol: '$',
  },
  {
    flag: 'fi fi-eu',
    code: 'EUR',
    desc: 'Euro',
    symbol: '€',
  },
  {
    flag: 'fi fi-gb',
    code: 'GBP',
    desc: 'British Pound',
    symbol: '£',
  },
  {
    flag: 'fi fi-in',
    code: 'INR',
    desc: 'Indian Rupee',
    symbol: '₹',
  },
  {
    flag: 'fi fi-au',
    code: 'AUD',
    desc: 'Australian Dollar',
    symbol: '$',
  },
  {
    flag: 'fi fi-ca',
    code: 'CAD',
    desc: 'Canadian Dollar',
    symbol: '$',
  },
  {
    flag: 'fi fi-sg',
    code: 'SGD',
    desc: 'Singapore Dollar',
    symbol: '$',
  },
  {
    flag: 'fi fi-ch',
    code: 'CHF',
    desc: 'Swiss Franc',
    symbol: 'CHF',
  },
  {
    flag: 'fi fi-my',
    code: 'MYR',
    desc: 'Malaysian Ringgit',
    symbol: 'RM',
  },
  {
    flag: 'fi fi-jp',
    code: 'JPY',
    desc: 'Japanese Yen',
    symbol: '¥',
  },
  {
    flag: 'fi fi-cn',
    code: 'CNY',
    desc: 'Chinese Yuan Renminbi',
    symbol: '¥',
  },
  {
    flag: 'fi fi-nz',
    code: 'NZD',
    desc: 'New Zealand Dollar',
    symbol: '$',
  },
  {
    flag: 'fi fi-th',
    code: 'THB',
    desc: 'Thai Baht',
    symbol: '฿',
  },
  {
    flag: 'fi fi-hu',
    code: 'HUF',
    desc: 'Hungarian Forint',
    symbol: 'Ft',
  },
  {
    flag: 'fi fi-ae',
    code: 'AED',
    desc: 'Emirati Dirham',
    symbol: 'د.إ',
  },
  {
    flag: 'fi fi-hk',
    code: 'HKD',
    desc: 'Hong Kong Dollar',
    symbol: '$',
  },
  {
    flag: 'fi fi-mx',
    code: 'MXN',
    desc: 'Mexican Peso',
    symbol: '$',
  },
  {
    flag: 'fi fi-za',
    code: 'ZAR',
    desc: 'South African Rand',
    symbol: 'R',
  },
  {
    flag: 'fi fi-ph',
    code: 'PHP',
    desc: 'Philippine Peso',
    symbol: '₱',
  },
  {
    flag: 'fi fi-se',
    code: 'SEK',
    desc: 'Swedish Krona',
    symbol: 'kr',
  },
  {
    flag: 'fi fi-id',
    code: 'IDR',
    desc: 'Indonesian Rupiah',
    symbol: 'Rp',
  },
  {
    flag: 'fi fi-sa',
    code: 'SAR',
    desc: 'Saudi Arabian Riyal',
    symbol: '﷼',
  },
  {
    flag: 'fi fi-br',
    code: 'BRL',
    desc: 'Brazilian Real',
    symbol: 'R$',
  },
  {
    flag: 'fi fi-tr',
    code: 'TRY',
    desc: 'Turkish Lira',
    symbol: '₺',
  },
  {
    flag: 'fi fi-ke',
    code: 'KES',
    desc: 'Kenyan Shilling',
    symbol: 'KSh',
  },
  {
    flag: 'fi fi-kr',
    code: 'KRW',
    desc: 'South Korean Won',
    symbol: '₩',
  },
  {
    flag: 'fi fi-eg',
    code: 'EGP',
    desc: 'Egyptian Pound',
    symbol: '£',
  },
  {
    flag: 'fi fi-iq',
    code: 'IQD',
    desc: 'Iraqi Dinar',
    symbol: 'ع.د',
  },
];
